### ISSUE TITLE
Cant download files

### ISSUE THREAD

**Issue by arieimer** [tburgeson/The-Jimmy-Archive#1]
downloading files are broken

**Comment by tburgeson** [comment]
Yeah, I need to find an index that works on GitHub pages until I move it back to my server

**Comment by tburgeson** [comment]
Currently I am adding download buttons on the videos page next to the watch buttons and will probably be adding an index in the files directory

**Comment by tburgeson** [comment]
Ok I finally added the index, files can be downloaded now
