### ISSUE TITLE
File downloader off screen

### ISSUE THREAD

**Issue by arieimer** [tburgeson/The-Jimmy-Archive#3]
<img width="1149" alt="Screen Shot 2021-03-24 at 9 25 29 AM" src="https://user-images.githubusercontent.com/54780610/112326983-09ec0800-8c83-11eb-8f38-ce6df5bb1189.png">

**Comment by tburgeson** [comment]
You don't need to have the view tab open while trying to download something?

**Comment by arieimer** [comment]
ok

**Comment by tburgeson** [comment]
![image](https://user-images.githubusercontent.com/56371693/112338668-fa71bc80-8c8c-11eb-9b77-801799848601.png)

**Comment by tburgeson** [comment]
Works fine like that
